language: ruby
sudo: false
rvm:
  - "2.0.0"

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rake spec

before_script:
- psql -c 'create database travis_ci_test;' -U postgres
before_script:
  - cp config/database.yml.travis config/database.yml
